name: Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install SSH Key
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Disable strict host key checking
      run: |
        mkdir -p ~/.ssh
        echo -e "Host *\n\tStrictHostKeyChecking no\n" > ~/.ssh/config

    - name: Deploy via SSH
      run: |
        ssh -o ServerAliveInterval=60 ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
          # Navigate to app directory
          cd ~/TalantonCore-assign

          # Pull latest changes
          git pull origin main

          # Install dependencies & build
          npm install
          npm run build

          # Create or update .env.production file
          echo "MONGODB_URI=${{ secrets.MONGODB_URI }}" > .env.production
          echo "AWS_REGION=${{ secrets.AWS_REGION }}" >> .env.production
          echo "AWS_S3_BUCKET=${{ secrets.AWS_S3_BUCKET }}" >> .env.production
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> .env.production
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> .env.production

          # Restart or start app using PM2 with environment variables
          pm2 restart next-app || pm2 start npm --name "next-app" -- start --env production

          # Save PM2 process list
          pm2 save
        EOF
